export const dataQuest = [
    {
        quest: 'Apakah bisa mengambil jurusan s2 yang tidak linier di amerika? Dan bagaimana ketentuannya',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        status: 'Ikuti',
        rate: '120',
        poin: '10 poin',
    },
    {
        quest: 'Mengapa seringkali motivator menasehati agar kita berhenti bermedsos dan menggunakan gadget? Bukankah dari medsos dan gadget kita juga mendapat pengetahuan, keterampilan serta wawasan yang bisa meningkatkan produktifitas?',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        status: 'Ikuti',
        rate: '120',
        poin: '10 poin',
    },
    {
        quest: 'Bagaimana cara mengatasi error tentang penginstallan flutter?',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        status: 'Ikuti',
        rate: '120',
        poin: '10 poin',
    },
    {
        quest: 'Bagaimana cara mengatasi error tentang penginstallan tailwind dan react?',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        status: 'Ikuti',
        rate: '120',
        poin: '10 poin',
    },
    {
        quest: 'Bagaimana cara mengatasi error tentang penginstallan flutter?',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        rate: '120',
        poin: '10 poin',
    },
    {
        quest: 'Apa hal dasar yang wajib dikuasai untuk mempelajari jaringan dengan menggunakan mikrotik?',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        rate: '120',
        poin: '10 poin',
    },
    {
        quest: 'Bisakah anda menjelaskan maksud dari Fitts Law pada penerapan pembuatan design web?',
        respon: '20 rb jawaban',
        date: 'Terakhir dilihat 13 jan',
        rate: '120',
        poin: '10 poin',
    },
]